services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    command: -p ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    restart: unless-stopped
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DB_USER} -p ${DB_PORT}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  liquibase:
    image: liquibase/liquibase
    volumes:
      - ../db:/liquibase/changelog
    depends_on:
      postgres:
        condition: service_healthy
    command: --changeLogFile=db.changelog-master.xml --searchPath=/liquibase/changelog --url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME} --username=${DB_USER} --password=${DB_PASSWORD} update
    networks:
      - backend

  app:
    build:
      context: ../
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    healthcheck:
      test: [ "CMD", "wget", "-qO-", "http://localhost:9600/ready" ]
      interval: 10s
      timeout: 2s
      retries: 3
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - DATABASE_READ_URL=${DATABASE_READ_URL}
      - DATABASE_WRITE_URL=${DATABASE_WRITE_URL}
    networks:
      - backend

networks:
  backend:

volumes:
  dbdata:


